### PR TITLE
Add option to specify JDK_ARCH

### PR DESCRIPTION
**Pull request by srware**
Currently the JDK arch is hard-coded to 'amd64' which limits compatibility. This patch adds an option to specify JDK_ARCH using an environment variable and if not set it defaults to 'amd64'.

### CODE REVIEW

**Comment by andrew-buckley** [comment]
Hi @srware, thanks for having a look at this. I'll have a look and discuss it with the rest of the team shortly. 

From first glance it looks good! The only thing I could see potentially being an issue is setting environment variables on the users behalf in the CMakeLists.txt file unless it's really necessary. I'd suggest using a CMake variable to store the architecture, check if the environment variable exists and if it does set the variable to that, otherwise leave it at a default.

The other thing I'd say is to please update the Java docs in the repo to describe how users may change the default architecture.

Thanks again!

**Comment by srware** [comment]
I agree, a CMake variable would be the preferred option. I will update the pull request and update the docs also.

Thanks.

**Comment by avranju** [comment]
Also, I wonder if we cannot automatically determine what the CPU architecture is given that we have `JAVA_HOME`.

**Comment by andrew-buckley** [comment]
I don't *think* so, the structure is identical (on linux) until you reach JAVA_HOME/lib/{architecture}. Additionally, the name of the JAVA_HOME could technically be anything

**Comment by srware** [comment]
With that in mind what should take precedence, CMake variable or environment variable? I would say if someone specifies JDK_ARCH in their cmake command that should override environment?

**Comment by avranju** [comment]
Agree. So, in summary, if `JDK_ARCH` is not defined and `ENV_{JDK_ARCH}` is, then assign `ENV_{JDK_ARCH}` to `JDK_ARCH`. Otherwise, assign `amd64` to `JDK_ARCH`.

**Comment by srware** [comment]
The pull request commits have been updated to reflect the changes we talked about. Let me know what you think.

Thanks.

**Comment by andrew-buckley** [comment]
Thanks, @srware. I'll be merging this in today.

**Pull request merged**
