### PR TITLE
display message flow for users

### PR DESCRIPTION
**Pull request by yaweiw**

### CODE REVIEW

**Comment by yaweiw** [comment]
Sample output before:
[2016:11:16T01:37:04] Temperature: (18.031250, 25.500000)
[2016:11:16T01:37:05] Temperature: (18.031250, 25.500000)
[2016:11:16T01:37:06] Temperature: (17.937500, 25.500000)

after:
[2016:11:16T01:37:04][BLE Module -> IoTHub Module -> Azure IoT Hub] Temperature: (18.031250, 25.500000)
[2016:11:16T01:37:05][BLE Module -> IoTHub Module -> Azure IoT Hub] Temperature: (18.031250, 25.500000)
[2016:11:16T01:37:06][BLE Module -> IoTHub Module -> Azure IoT Hub] Temperature: (17.937500, 25.500000)

**Comment by yaweiw** [comment]
@damonbarry

**Comment by yaweiw** [comment]
@damonbarry

**Comment by damonbarry** [comment]
@yaweiw  You are hard-coding information about the gateway's configuration into the BLE printer module. This is not a good approach because the user can configure the gateway differently, and then the printed messages will be incorrect.

What problem are you trying to solve? If you want to give the user a clearer picture of the gateway configuration, then we'd probably want to add logging to the gateway core that lists the loaded modules and their connections to each other--and it only prints it *once*, when the gateway loads.

**Pull request closed without merging**
