### PR TITLE
Allow create Field Gateway inside c# process

### PR DESCRIPTION
**Pull request by AdamMachera**
I would like to be able to create field gateway inside c# process using this syntax
this.gatewayHandle = NativeDotNetHostWrapper.GatewayCreateFromJson(GatewayConfigName);

it would allow us hosting field gateway e.g. inside windows service written in c#.

### CODE REVIEW

**Comment by darobs** [comment]
Hi @AdamMachera, I really like the idea behind this, but I've got a branch going into develop soon (next few business days) that should make this pull request look better.  I'm changing the build so that the gateway library is a DLL in Windows, which will eliminate the need for that thin layer in the dotnet binding.

Is it OK if we hold off on this pull request for my change to go in, or do you have an immediate need?  

Thanks, 
Dave 

The working branch is here: https://github.com/darobs/azure-iot-gateway-sdk/tree/gateway_shared_libs

**Comment by AdamMachera** [comment]
Yes, sure that's not a problem.
BTW I have a question with gateway in new library will we be able to use in
one process modules from different worlds (.NET module in same process with
Node module)?

Regards,
Adam.


2016-12-15 20:44 GMT+01:00 darobs <notifications@github.com>:

**Comment by avranju** [comment]
Yes, that is possible right now. You can combine multiple language bindings in the same gateway process.

**Comment by AdamMachera** [comment]
Hi,


Wanted to ask additional question.

I have windows service (FieldGatewayService) that creates FG from c#.



I have flag that allows me to run this application (FieldGatewayService)
from command line if I pass “/DebugInConsole” parameter. Such invocation
works ok.

If I was running app from VS 2015 it was stopping without any exception
same way as running it as windows service (even when I enabled in exception
settings window to catch all types of exceptions both CLR, native, nodejs).

I had to check below setting to be able to run it from VS

"Enable native code debugging"



Now, I installed application as windows service and it is being shutdown
once it tries to instantiate node component.

In Event Viewer in System I see message “The FG2TestDeb2 service terminated
unexpectedly.  It has done this 4 time(s). “



I installed DebugDiag application and it shows



[image:
mhtml:file://C:\Program%20Files\DebugDiag\Reports\CrashHang_Report__Date_12_21_2016__Time_05_12_12PM__14.mht!res/error.png]
Error

In FIELDG~3.DMP the assembly instruction at *KERNELBASE!RaiseException+68*
in *C:\Windows\System32\KERNELBASE.dll* from *Microsoft Corporation* has
caused a *CLR Exception* on thread *11* <#9836:5Thread2712> with the
following error information:

    Type:

*NOT_FOUND*

    Message:

NOT_FOUND



Please follow up with vendor *Microsoft Corporation* for problem resolution
concerning the following file: *C:\Windows\System32\KERNELBASE.dll.*



*Thread 11 - System ID 2712*

Entry point

  *ntdll!RtlUserThreadStart+21*

Create time

  *21.12.2016 16:26:49*

Time spent in user mode

  *0 Days 00:00:00.171*

Time spent in kernel mode

  *0 Days 00:00:00.031*



This thread is not fully resolved and may or may not be a problem. Further
analysis of these threads may be required.

*.NET Call Stack*

*Function*


*Full Call Stack*

*Function*

*  Source*

KERNELBASE!RaiseException+68



clr!RaiseTheExceptionInternalOnly+2aa



clr!IL_Throw+10b



0x00007ff9`f10388cb



mscorlib_ni+48674e



mscorlib_ni+4865e7



mscorlib_ni+4d29fd



mscorlib_ni+4d9c62



mscorlib_ni+4a0244



mscorlib_ni+4d8bf5



mscorlib_ni+4d151d



mscorlib_ni+4d1438



0x00007ff9`f1039118



mscorlib_ni+48674e



mscorlib_ni+4865e7



mscorlib_ni+4d29fd



mscorlib_ni+4d9c62



mscorlib_ni+4a0244



mscorlib_ni+49fdb7



mscorlib_ni+4d1d5c



mscorlib_ni+f2668f



mscorlib_ni+48674e



mscorlib_ni+4865e7



mscorlib_ni+4d29fd



mscorlib_ni+4d9c62



mscorlib_ni+4a0244



mscorlib_ni+4da82d



mscorlib_ni+4da914



mscorlib_ni+f2769d



mscorlib_ni+48674e



mscorlib_ni+4865e7



mscorlib_ni+4d29fd



mscorlib_ni+4d9c62



mscorlib_ni+4a0244



mscorlib_ni+4da82d



mscorlib_ni+f5ceb6



mscorlib_ni+f5cfce



mscorlib_ni+48674e



mscorlib_ni+4865e7



mscorlib_ni+f23fa6



mscorlib_ni+4a0287



mscorlib_ni+4cfe44



mscorlib_ni+4d0c00



mscorlib_ni+4d0303



mscorlib_ni+48fa10



clr!CallDescrWorkerInternal+83



clr!CallDescrWorkerWithHandler+4e



clr!MethodDescCallSite::CallTargetWorker+f8



clr!QueueUserWorkItemManagedCallback+2a



clr!Frame::Push+59



clr!PEDecoder::GetNativeCodeManagerTable+170



clr!PEDecoder::GetNativeCodeManagerTable+99



clr!QueueUserWorkItemManagedCallback+67



clr!ManagedPerAppDomainTPCount::DispatchWorkItem+a0



clr!ThreadpoolMgr::ExecuteWorkRequest+64



clr!ThreadpoolMgr::WorkerThreadStart+f5



clr!Thread::intermediateThreadProc+86



kernel32!BaseThreadInitThunk+14



ntdll!RtlUserThreadStart+21



To do some more testing I created second windows called FGHoster that only
runs this application as process



ProcessStartInfo psi = new ProcessStartInfo(
@"c:\s\src\Field\FieldGatewayService\bin\Debug\FieldGatewayService.exe",
$"/DebugInConsole");

            psi.CreateNoWindow = true;

            psi.WorkingDirectory =
@"c:\s\src\Field\FieldGatewayService\bin\Debug\";

            psi.RedirectStandardError = true;

            psi.RedirectStandardOutput = true;

            psi.UseShellExecute = false;

            try

            {

                process = Process.Start(psi);

            }

            catch (Exception ex)

            {

                File.WriteAllText(System.AppDomain
.CurrentDomain.BaseDirectory + "log.txt", ex.ToString());

            }

In this scenario it works I see that FieldGatewayService logs data.



Don’t know what can I do as next step of investigation.



Regards,

Adam.

2016-12-15 20:59 GMT+01:00 Rajasekharan Vengalil <notifications@github.com>:

**Comment by aribeironovaes** [comment]
Hi Adam, 

I would need more information to help you debugging this. 
Some suggestion that comes to mind: 
1-Can you have a clean version of the gateway (for example without any modules) running? If you do that, does it still crashs/shutdown after some time?

2-If 1 is not true, I would be adding slowly modules and investigate which one is causing trouble or is causing gateway to crash. 

Since Gateway now is a single process, any module can be causing this issue. 

Let us know... Responses may be slow these days, but I will keep an eye on your questions and try to help you out. 

If you also can, send me the bits you are testing with repro steps and I can try to help you debugging this. 

Thanks a lot, 

Angelo Ribeiro.

**Comment by AdamMachera** [comment]
Hi Angelo,

I did as you suggested. Left only simple node module and native logger
module.
I finally found out what was the problem.

If I run code from console application once FG is created from json code is
working and is using relative paths (both for native c++ and node modules).
    {
      "name": "node_sensor",
      "loader": {
        "name": "node",
        "entrypoint": {
          "main.path": "Modules\\\\node\\\\sensor.js"
        }
      },
      "args": null
    }

If I run code from windows service FG is not able to use relative paths for
node (for native c++ logger module it works).
Above configuration is not working.
I changed configuration to point to full path and it works in widows
service as well
    {
      "name": "node_sensor",
      "loader": {
        "name": "node",
        "entrypoint": {
          "main.path": "c:\\\\s\\\\TetraPak\\\\src\\\
\Field\\\\FieldGatewayService\\\\bin\\\\Debug\\\\Modules\\\\
node\\\\sensor.js"
        }
      },
      "args": null
    }


To replicate this issue on your side you can create simple Windows Service
and in OnStart method

ProcessStartInfo psi = new
ProcessStartInfo(@"c:\s\Edge_Package_Loader\temp\Gateway_Demo\nodejs_simple_sample.exe",
$"gateway.json");
psi.CreateNoWindow = true;
psi.WorkingDirectory = @"c:\s\Edge_Package_Loader\temp\Gateway_Demo\";
psi.RedirectStandardError = true;
psi.RedirectStandardOutput = true;
psi.UseShellExecute = false;try
{
    process = Process.Start(psi);
}catch (Exception ex)
{
    File.WriteAllText(System.AppDomain.CurrentDomain.BaseDirectory +
"log.txt", ex.ToString());
}

If you remove full path and use relative
    {
      "name": "node_sensor",
      "loader": {
        "name": "node",
        "entrypoint": {
          "main.path": "Modules\\\\sensor.js"
        }
      },
      "args": null
    }

Nothing will work but also no logging is available to investigate issue.

Regards,
Adam.


2016-12-22 1:04 GMT+01:00 Angelo Ribeiro <notifications@github.com>:

**Comment by AdamMachera** [comment]
So it seems that problem is not solved.
Today when I started asa.js module that uses require syntax

var TStreamsMain = require('TStreamsMain');var azureStorage =
require('azure-storage');var fs = require('fs');

Service is crashing without any information.

I changed sensor module to confirm this behavior

'use strict';
 var fs = require('azure-storage');
 /// Sensor module
module.exports = {
    messageBus: null,
    configuration: null,
    shouldStop: false,

    create: function (messageBus, configuration) {
        this.messageBus = messageBus;
        this.configuration = configuration;

When service starts and hits moment where FG should be created from
config it is failing on sensor module creation.

If I remove var fs = require('azure-storage') it works.

I'm not very fluent in node world.

My service is installed here:

c:\s\TetraPak\src\Field\FieldGatewayService\bin\Debug\FieldGatewayService.exe

Node asa.js and sensor.js are situated here

c:\s\TetraPak\src\Field\FieldGatewayService\bin\Debug\Modules\Node

Required node_modules are installed

c:\s\TetraPak\src\Field\FieldGatewayService\bin\Debug\Modules\node\node_modules\


Regards,

Adam.





2016-12-22 22:07 GMT+01:00 Adam Machera <adam.machera@gmail.com>:

**Comment by aribeironovaes** [comment]
Hi Adam, 

Can you open a github issue with all the information you have that would help us to debug this issue? 

I think it's better to track and other members of the team to follow up on this if it's a github issue. 

Thanks a lot, 

Angelo Ribeiro.

**Comment by AdamMachera** [comment]
Hi Angelo,

I have opened issue #83.

Inside issue I have described how to replicate problem and published simple
solution into github showing problem.

Regards,
Adam.

2016-12-28 0:10 GMT+01:00 Angelo Ribeiro <notifications@github.com>:

**Comment by damonbarry** [comment]
@AdamMachera, as it turns out we're already working on a very similar feature--we will be providing a .NET wrapper around the gateway SDK. But it has some fundamental differences: we'll be exposing a more complete API set (not just the two functions), and it will be in its own assembly, rather than amending the .NET binding assembly. I don't think we should take this PR in light of the work we're doing.

**Comment by AdamMachera** [comment]
Do you have any road map when it is going to be ready?

Regards,
Adam.

2017-01-13 23:11 GMT+01:00 Damon Barry <notifications@github.com>:

**Comment by damonbarry** [comment]
We're hoping to have it in February.

**Pull request closed without merging**
